apiVersion: v1
kind: Pod
metadata:
  name: my-pod-liveness
spec:
  containers:
  - name: my-container
    image: nginx
    livenessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 3
      periodSeconds: 3
