apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  USERNAME: bXl1c2Vy
  PASSWORD: bXlwYXNzd29yZA==
---
apiVersion: v1
kind: Pod
metadata:
  name: my-pod-secret-env
spec:
  containers:
  - name: my-container
    image: nginx
    env:
    - name: MY_USERNAME
      valueFrom:
        secretKeyRef:
          name: my-secret
          key: USERNAME
    - name: MY_PASSWORD
      valueFrom:
        secretKeyRef:
          name: my-secret
          key: PASSWORD
