apiVersion: batch/v1
kind: Job
metadata:
  name: my-job
spec:
  template:
    spec:
      initContainers:
      - name: init-data-generator
        image: busybox
        command: ['sh', '-c', 'echo "Data synchronized" > /data/status.txt']
        volumeMounts:
        - name: shared-data
          mountPath: /data
      containers:
      - name: my-container
        image: nginx
        command: ['sh', '-c', 'cat /data/status.txt; sleep 10']
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3
        volumeMounts:
        - name: shared-data
          mountPath: /data
      volumes:
      - name: shared-data
        emptyDir: {}
      restartPolicy: OnFailure
  backoffLimit: 4
